[project]
name = "nx-workspace"
version = "1.0.0"
dependencies = [
  "crossword-solver-adapter-clue-extractor",
  "crossword-solver-create-puzzle",
  "crossword-solver-domain-entities",
  "crossword-solver-domain-use-case",
  "crossword-solver-image"
]

[tool.uv.workspace]
members = [
  "packages/lambdas/python-lambdas/adapter/clue_extractor",
  "packages/lambdas/python-lambdas/create-puzzle",
  "packages/lambdas/python-lambdas/domain/entities",
  "packages/lambdas/python-lambdas/domain/use-case",
  "packages/lambdas/python-lambdas/image"
]

[tool.uv.sources.crossword-solver-adapter-clue-extractor]
workspace = true

[tool.uv.sources.crossword-solver-create-puzzle]
workspace = true

[tool.uv.sources.crossword-solver-domain-entities]
workspace = true

[tool.uv.sources.crossword-solver-domain-use-case]
workspace = true

[tool.uv.sources.crossword-solver-image]
workspace = true

[dependency-groups]
dev = [
  "ruff==0.16.10",
  "autopep8>=2.3.1",
  "pytest>=8.3.4",
  "pytest-sugar>=1.0.0",
  "pytest-cov>=6.0.0",
  "pytest-html>=4.1.1",
  "ty==0.0.84",
  "pytest-httpserver>=1.2.0",
]
