[project]
name = "nx-workspace"
version = "1.0.0"
dependencies = [ "crossword-solver-create-puzzle", "crossword-solver-domain-entities" ]

[tool.uv.workspace]
members = [
  "packages/lambdas/python-lambdas/create-puzzle",
  "packages/lambdas/python-lambdas/domain/entities"
]

[tool.uv.sources.crossword-solver-create-puzzle]
workspace = true

[tool.uv.sources.crossword-solver-domain-entities]
workspace = true

[dependency-groups]
dev = [
  "ruff==0.16.9",
  "autopep8>=2.3.1",
  "pytest>=8.3.4",
  "pytest-sugar>=1.0.0",
  "pytest-cov>=6.0.0",
  "pytest-html>=4.1.1",
  "ty==0.0.84"
]
