sonar.projectKey=michaelruocco_crossword-solver
sonar.organization=michaelruocco

sonar.sources=packages
sonar.tests=packages
sonar.exclusions=**/tests/**,**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/.venv/**,**/dist/**
sonar.test.inclusions=**/tests/**,**/*.spec.ts,**/*.test.ts
sonar.coverage.exclusions=**/*.config.ts,**/*.config.mts

sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage/packages/lambdas/python-lambdas/**/coverage.xml
sonar.javascript.lcov.reportPaths=coverage/packages/lambdas/ts-lambdas/lcov.info
